name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  x86-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86.sh
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh
  x86-64-linux-O0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64-O0.sh
  x86-64-linux-O1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64-O1.sh
  x86-64-linux-O2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64-O2.sh
  x86-64-linux-O3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64-O3.sh
  x86_64-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/macos/build-test-x86_64.sh
  jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/jvm/build-test-jvm.sh
  wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: bash ./ci/wasm/build-test-wasm.sh

