name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  x86-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86.sh
  x86-linux-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86.sh -wfts
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh
  x86_64-linux-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -wfts
#TODO  x86-64-linux-O0:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Build and Test
#        run: bash ./ci/linux/build-test-x86_64.sh -O0
  x86-64-linux-O1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -O1
  x86-64-linux-O1-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -O1 -wfts
  x86-64-linux-fp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -rt.fp=true
  x86-64-linux-fp-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -rt.fp=true -wfts
  x86-64-linux-O2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -O2
  x86-64-linux-O2-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -O2 -wfts
  x86-64-linux-unbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -unbox-variants
  x86-64-linux-unbox-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -unbox-variants -wfts
  x86-64-linux-unbox-o2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -unbox-variants -O2
  x86-64-linux-unbox-O2-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/build-test-x86_64.sh -unbox-variants -O2 -wfts
#  x86-64-linux-O3:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Build and Test
#        run: bash ./ci/linux/build-test-x86_64.sh -O3
#  x86_64-macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Build and Test
#        run: bash ./ci/macos/build-test-x86_64.sh
  x86-64-linux-licm:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/linux/licm-microbench.sh
  x86_64-macos-bootstrap:
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: AENEAS_TEST=bootstrap bash ./ci/macos/build-test-x86_64.sh
  x86_64-macos-current:
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: AENEAS_TEST=current bash ./ci/macos/build-test-x86_64.sh
  jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/jvm/build-test-jvm.sh
  jvm-O2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/jvm/build-test-jvm.sh -O2
  jvm-unbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/jvm/build-test-jvm.sh -unbox-variants
  wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/wasm/build-test-wasm.sh
  wasm-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/wasm/build-test-wasm.sh -wfts
  wasm-O2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/wasm/build-test-wasm.sh -O2
  wasm-O2-wfts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: bash ./ci/wasm/build-test-wasm.sh -O2
  wasm-gc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh
  wasm-gc-O2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh -O2
  wasm-gc-og:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh -wasm-gc-one-group
  wasm-gc-O2-og:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh -O2 -wasm-gc-one-group
  wasm-gc-rt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh -wasm-gc-use-ref-test
  wasm-gc-O2-rt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Build and Test
        run: bash ./ci/wasm-gc/build-test-wasm-gc.sh -O2 -wasm-gc-use-ref-test
